WIDTH = 1280
HEIGHT = 720

MODEL_PATH = "models/hand_landmarker.task"

OBJECT_SIZE = 80

SMOOTHING = 0.25

CAMERA_INDEX = 0
FPS = 60

MIN_HAND_DETECTION_CONFIDENCE = 0.7
MIN_HAND_PRESENCE_CONFIDENCE = 0.7
MIN_TRACKING_CONFIDENCE = 0.7